// <auto-generated />
using BusinessAdmin.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAdmin.DataAccess.Migrations.TraData
{
    [DbContext(typeof(TraDataContext))]
    [Migration("20230413064228_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BusinessAdmin.DataAccess.Models.TradeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllTra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NorTra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeTra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TradeData");
                });
#pragma warning restore 612, 618
        }
    }
}
