// <auto-generated />
using System;
using BusinessAdmin.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessAdmin.DataAccess.Migrations.ManagerReqList
{
    [DbContext(typeof(ManagerReqListContext))]
    partial class ManagerReqListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BusinessAdmin.DataAccess.Models.ManagerReqList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeoPle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReqTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagerReqList");
                });
#pragma warning restore 612, 618
        }
    }
}
